### ISSUE TITLE
Trying out maestro-ng, getting: ConnectionError: ('Connection aborted.', BadStatusLine("''",))

### ISSUE THREAD

**Issue by jorge-marques** [signalfx/maestro-ng#149]
Hi, I'm trying out maestro but having some trouble:

Here's my test maestro file:

    name: APP_NAME

    ships:
      vm:
        ip: xx.xx.xx.xx
        ssh_tunnel:
          user: root
          key: /path/to/my/key

    services:
      wp:
        image: tutum/wordpress
          instances:
            wp:
              ship: vm

I've tried running `maestro pull` bug get `ConnectionError: ('Connection aborted.', BadStatusLine("''",))`
The error seems to come from docker-py. I'm running docker 1.7.1. Anyone experiencing similar issues?
Any help would be very appreciated.

**Comment by mpetazzoni** [comment]
Can you try without using an SSH tunnel? `BadStatusLine` is something that comes out of `python-requests`, so somehow the HTTP request made to the Docker daemon didn't work, so the first thing to try is a more "direct" connection to the daemon.

**Comment by mpetazzoni** [comment]
No response; closing.
