### ISSUE TITLE
Split up Index page

### ISSUE THREAD

**Issue by Ceasar** [signalfx/maestro-ng#158]
As mentioned in #157, the index page should be split up into separate pages to make it more manageable.

Presently, there are sections for:

1. Introduction
2. Orchestration
3. Environment description
4. Defining dependencies
5. Port mapping syntax
6. Port mapping and named ports
7. Volume bindings
8. Lifecycle checks
9. Restart policy
10. How Maestro orchestrates and service auto-configuration
11. Links
12. Working with image registries
13. Examples of Docker images with maestro orchestration

I think (1) and (2) should stay for certain. They can be combined, and basically explains what Maestro is and what it's for.

(3) should be its own page. It's basically a reference for all of the available parameters in `maestro.yaml`.

The others I haven't really read. @mpetazzoni, you'd probably know better.

**Comment by mpetazzoni** [comment]
Yep, you're correct. 1 and 2 should remain in the index page. Everything else should be its own page, making sure we link correctly to them wherever we say "See <something> below". The last one (13. Examples) should be an index page inside the examples sub directory.
