### ISSUE TITLE
Cannot add volume mode to make selinux work

### ISSUE THREAD

**Issue by wt** [signalfx/maestro-ng#167]
I need to be able to add the "Z" option to the docker volume specs so that the docker containers can write to bind mounted volumes from the host. Adding a "mode" of "Z" appears not to pass Z through.

Here's a longer description:
http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/

**Comment by mpetazzoni** [comment]
Good find. I'll work on making this work ASAP.
