### ISSUE TITLE
support the unless-stopped restart policy

### ISSUE THREAD

**Issue by petrkalina** [signalfx/maestro-ng#181]
add support to the `unless-stopped` restart policy (see https://docs.docker.com/engine/reference/run/) 

IMO this is due to this line in https://github.com/signalfx/maestro-ng/blob/master/maestro/entities.py

<pre>
# Possible values for the restart policy type.
_VALID_RESTART_POLICIES = ['no', 'always', 'on-failure']
</pre>

so the fix should be trivial

**Comment by petrkalina** [comment]
when is the next release planned so I can apply this fix in production?

**Comment by mpetazzoni** [comment]
Just released 0.4.2 with the recent changes, including this fix. Enjoy!
