### ISSUE TITLE
Support for container label

### ISSUE THREAD

**Issue by lvjp** [signalfx/maestro-ng#202]
It would be great to be able to add label to container like you can do with the command `docker run --label "key=value"`.

This can permit updating third party tools based on label of launched container.
For example [traefik](https://docs.traefik.io/configuration/backends/docker/) implement a dynamic reverse proxy based on label...

The used `docker-py` can accept label within the [create_container](https://docker-py.readthedocs.io/en/stable/api.html?highlight=create_container#docker.api.container.ContainerApiMixin.create_container) member function called at [tasks.py:220](https://github.com/signalfx/maestro-ng/blob/9ca4165db864309df1022cbe63609b7b6baee100/maestro/plays/tasks.py#L220).

**Comment by mpetazzoni** [comment]
This should now be available in 0.7.0!

**Comment by lvjp** [comment]
Thank you for your reactivity. It's now in our test environment and will be used soon production.
