### ISSUE TITLE
Add support for externalised env files

### ISSUE THREAD

**Issue by petrkalina** [signalfx/maestro-ng#203]
Allow specifying env mapping in ".env" file like in docker compose and allow including this file in container definition.

**Comment by mpetazzoni** [comment]
Can you clarify your request? Do you mean that you want the ability to include the contents of a file like Docker Compose's `env_file`s (https://docs.docker.com/compose/compose-file/#env_file) as environment to a container?

**Comment by petrkalina** [comment]
exactly!

**Comment by petrkalina** [comment]
The `.env` files are also supported by `docker run` command i.e.

```
docker run --rm --env-file  ./my.env ...
```

```
$ cat ./my.env 
ENV_VAR1=value
ENV_VAR2=value
```

which can be useful in executing specific pre-configured commands via docker - which is for example use-case I would be after, if I could manage env variables in `.env` files. Another good reason is possibility to reuse the same `.env` file for multiple containers preventing duplicities.

**Comment by mpetazzoni** [comment]
Maestro's environment file is templated which typically help with those situations. The fact that `docker run` itself supports env files means that Maestro doesn't actually have to do any parsing of those env files and just passes it along to Docker. That makes implementation easier.

**Comment by petrkalina** [comment]
hello .. just a question - when do you think you will have time to add this?

**Comment by mpetazzoni** [comment]
@petrkalina support for this just landed in `master`. Try it out and let me know what you think!

**Comment by petrkalina** [comment]
verified! But I found out it is not documented in the docs (https://maestro-ng.readthedocs.io/en/latest/environment.html?highlight=env)

```
    busybox:
        image: busybox
        instances:
            busybox1:
                ship: ship1
                envfile: /tmp/busybox1.env
                command: env
```

```
$ cat /tmp/busybox1.env
TESTVAR=test_value
```

```
$ maestro -f test.yaml start
  #  INSTANCE                                 SERVICE              SHIP                                     CONTAINER                  STATUS    
  1. busybox1                                 busybox              ship1                              latest:2e7a891             started
```

```
docker logs busybox1 | grep TEST
TESTVAR=test_value
```

**Comment by petrkalina** [comment]
According to docker:

**Comment by mpetazzoni** [comment]
@petrkalina Sorry about the docs, they didn't rebuild because the main branch was renamed (from master) and readthedocs was still trying to build from the now non-existent branch! Fixed now: https://maestro-ng.readthedocs.io/en/main/environment.html#service-instances

As for the empty lines, as you see I'm just using `docker.utils.parse_env_file()`, which should correctly skip empty lines: https://github.com/docker/docker-py/blame/master/docker/utils/utils.py#L454-L456

Can you confirm which version of docker-py you are using?
